import { MapLayerConfig } from '../types';

export const INITIAL_MAP_LAYERS: MapLayerConfig[] = [
  {
    id: 'temperature',
    label: 'Atmospheric Temperature',
    category: 'Thermal & Weather',
    description: 'Ambient 2-meter air temperature (°C) derived from ground weather stations and reanalysis.',
    active: true,
    opacity: 0.85,
    legendUnits: '°C',
    legendColors: ['#10b981', '#f59e0b', '#f97316', '#ef4444', '#7f1d1d'],
  },
  {
    id: 'heatIndex',
    label: 'Heat Index (Feels Like)',
    category: 'Thermal & Weather',
    description: 'Apparent physiological heat stress combining ambient temperature and relative humidity.',
    active: false,
    opacity: 0.8,
    legendUnits: '°C Apparent',
    legendColors: ['#10b981', '#fbbf24', '#f97316', '#dc2626', '#581c87'],
  },
  {
    id: 'lst',
    label: 'Land Surface Temperature (LST)',
    category: 'Thermal & Weather',
    description: 'Direct thermal radiation from asphalt, building roofs, and soil measured via Landsat-8/9 & Sentinel-3 SLSTR.',
    active: true,
    opacity: 0.75,
    legendUnits: '°C Skin',
    legendColors: ['#22c55e', '#eab308', '#f97316', '#dc2626', '#4c0519'],
  },
  {
    id: 'vegetation',
    label: 'Vegetation / NDVI Index',
    category: 'Surface & Land-Use',
    description: 'Normalized Difference Vegetation Index (NDVI) showing living canopy density and evapo-transpirational cooling.',
    active: false,
    opacity: 0.7,
    legendUnits: 'NDVI (0.0 to 1.0)',
    legendColors: ['#f87171', '#fbbf24', '#86efac', '#22c55e', '#14532d'],
  },
  {
    id: 'treeCanopy',
    label: 'Tree Canopy Deficit Zones',
    category: 'Surface & Land-Use',
    description: 'Identifies high-priority public street corridors with under 10% canopy coverage.',
    active: false,
    opacity: 0.75,
    legendUnits: 'Canopy %',
    legendColors: ['#ef4444', '#f97316', '#eab308', '#22c55e'],
  },
  {
    id: 'roads',
    label: 'Asphalt & Road Density',
    category: 'Surface & Land-Use',
    description: 'Vector-mapped impervious road corridors exhibiting low albedo and high daytime solar heat retention.',
    active: true,
    opacity: 0.65,
    legendUnits: 'Impervious %',
    legendColors: ['#64748b', '#94a3b8', '#f97316', '#ef4444'],
  },
  {
    id: 'buildings',
    label: 'Building Density & 3D Mass',
    category: 'Surface & Land-Use',
    description: 'Structural building footprints, height canyons, and heat-absorbing roofing materials.',
    active: false,
    opacity: 0.65,
    legendUnits: 'Footprint Ratio',
    legendColors: ['#cbd5e1', '#94a3b8', '#ea580c', '#b91c1c'],
  },
  {
    id: 'traffic',
    label: 'Traffic & Vehicle Heat Flux',
    category: 'Anthropogenic',
    description: 'Real-time vehicle density, congestion slowdowns, and combustion exhaust/AC rejection heat.',
    active: false,
    opacity: 0.7,
    legendUnits: 'Heat Flux (W/m²)',
    legendColors: ['#22c55e', '#eab308', '#f97316', '#dc2626'],
  },
  {
    id: 'industrial',
    label: 'Industrial Thermal Emission',
    category: 'Anthropogenic',
    description: 'Manufacturing, chemical plants, thermal generators, and industrial boiler waste heat zones.',
    active: false,
    opacity: 0.8,
    legendUnits: 'Waste MW',
    legendColors: ['#facc15', '#f97316', '#ef4444', '#7f1d1d'],
  },
  {
    id: 'dataCenters',
    label: 'Known Infrastructure Facilities',
    category: 'Anthropogenic',
    description: 'Documented cooling facilities, server hubs, and electrical transmission nodes.',
    active: false,
    opacity: 0.9,
    legendUnits: 'Facility Tier',
    legendColors: ['#38bdf8', '#818cf8', '#c084fc'],
  },
  {
    id: 'population',
    label: 'Population Heat Exposure',
    category: 'Anthropogenic',
    description: 'Human density and vulnerable demographic exposure (elderly, outdoor workers).',
    active: false,
    opacity: 0.6,
    legendUnits: 'Persons/km²',
    legendColors: ['#10b981', '#f59e0b', '#ef4444', '#7f1d1d'],
  },
];
